services:
  - type: web
    name: bag-discord-bot
    env: node
    autoDeploy: true
    plan: free
    buildCommand: npm ci
    startCommand: npm run render-start
    healthCheckPath: /health
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: LOCATIONIQ_TOKEN
        sync: false
      - key: LEVEL_CARD_LOGO_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: "mel805/Bag-bot"
      - key: GITHUB_BACKUP_BRANCH
        value: "backup-data"
      - key: DATABASE_URL
        fromDatabase:
          name: bag-bot-db
          property: connectionString
      - key: ENABLE_MUSIC
        value: true
      - key: ENABLE_LOCAL_LAVALINK
        value: false
      - key: LAVALINK_NODES
        value: '[{"identifier":"lavalink-render-1","host":"lava-v3.ajieblogs.eu.org","port":443,"password":"https://dsc.gg/ajidevserver","secure":true,"retryAmount":3,"retryDelay":8000},{"identifier":"lavalink-render-2","host":"lavalink.oops.wtf","port":443,"password":"www.freelavalink.ga","secure":true,"retryAmount":3,"retryDelay":10000},{"identifier":"lavalink-render-fallback","host":"lavalink.devamop.in","port":443,"password":"DevamOP","secure":true,"retryAmount":2,"retryDelay":15000}]'
databases:
  - name: bag-bot-db
    plan: free
